name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug file structure
        run: ls -R

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Copy source code to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "app,bootstrap,config,database,public,resources,routes,storage,artisan,composer.json,composer.lock,vite.config.js,package-lock.json,package.json"
          target: "/www/wwwroot/backend"

      - name: Run deployment commands on VPS
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          command: |
            cd /www/wwwroot/backend

            echo "${{ secrets.LARAVEL_ENV }}" > .env

            echo "ğŸ“¦ Install dependencies..."
            composer install --no-dev --optimize-autoloader --no-interaction

            echo "âš™ï¸ Jalankan migrate..."
            php artisan migrate --force

            echo "ğŸ”‘ Cache config dan route..."
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Symblink running"
            php artisan storage:link

            echo "âœ… Deployment selesai!"
